### ISSUE TITLE
Borderless (sf::Style::None) acts as Fullscreen if resolution is max

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1284]
**sf::Style::None** works at exclusive fullscreen mode as in **sf::Style::Fullscreen** when resolution is at max. It works as windowed at smaller resolutions.

Skype's screenshare is showing black screen if it's borderless & max resolution. 
Screenshot programs also shows black, or captures a very very old frame.

**Comment by LaurentGomila** [comment]
Please use the forum to discuss issues. This tracker is for confirmed features and bugs.

And please provide a more complete description of your problem and environment (minimal code, OS, WM, version of SFML, etc.).

**Comment by naezith** [comment]
@LaurentGomila Please don't close it, it's a known bug. Many of my players reported this, I also experience it. [It also exists in the forum](https://en.sfml-dev.org/forums/index.php?topic=21802.msg154680). I didn't see a issue here so I created one.


`#include <SFML/Graphics.hpp>

int main() {
    sf::RenderWindow window;
    window.create(sf::VideoMode::getDesktopMode(), "Borderless Window", sf::Style::Fullscreen);

    while(window.isOpen()) {
        sf::Event event;
        while(window.pollEvent(event)) if(event.type == sf::Event::Closed)  window.close();

        window.clear(sf::Color::Red);
        window.display();
    }

    return 0;
}
`

**Comment by Jaex** [comment]
I'm developer of the screen capture software [ShareX](https://getsharex.com) and I was testing his game [Naezith](https://naezith.com) on Windows 10. To be able to take screen capture or record videos from his game I needed to change video settings from fullscreen to borderless. But I noticed when resolution is lower than my monitor size than it works as expected. But as soon as I change resolution to my monitor size then it switches to exclusive fullscreen mode automatically and it does not let me capture screenshots from the game. This means when game window resolution is same as my monitor then fullscreen `sf::Style::Fullscreen` and borderless `sf::Style::None` have no difference.

**Comment by Veltas** [comment]
This appears to happen for me as well, notionwm window manager on Linux. Code used:

```c++
#include <SFML/Graphics.hpp>

int main()
{
  // Try with your fullscreen resolution, and a lower one that's also supported e.g. 800x600
  sf::RenderWindow window(sf::VideoMode(800, 600), "SFML Window", sf::Style::None); // Borderless fullscreen if dimensions match resolution
  //sf::RenderWindow window(sf::VideoMode(800, 600), "SFML Window", sf::Style::Fullscreen); // Always fullscren

  while (window.isOpen()) {
    sf::Event event;
    while (window.pollEvent(event)) {
      if (event.type == sf::Event::Closed) {
        window.close();
      }
      window.clear();
      window.display();
    }
  }
}
```

**Comment by naezith** [comment]
Can you please open this one @LaurentGomila?

**Comment by eXpl0it3r** [comment]
> notionwm window manager on Linux

@Veltas: How did you determin this?

Since Linux and Windows share completely different implementations and APIs, I find it hard to believe that such an odd behavior is shared on both Windows and Linux.

**Comment by slx7R4GDZM** [comment]
>Question is, whether this is a "bug" in SFML or if it's something that one can disable in Windows.

Newer versions of Windows 10 have a "Disable fullscreen optimizations" setting in the compatibility tab of a program's property window. Not sure if that has anything to do with this or not.

**Comment by Veltas** [comment]
> How did you determin this?
@eXpl0it3r Not sure if I had exact same thing, just specifically had what I said in comment. I presumed that's what they meant from the title but maybe it's regarding it being exclusive fullscreen mode specifically?

I mentioned it anyway since the behaviour I saw isn't described in the docs. It may actually be related, I don't know how separated the implementations are.

**Comment by marukrap** [comment]
Last time I checked this issue, it seemed OpenGL and Windows DWM(Aero) related problems, but I couldn't find a clear solution.

So, in my case, I'm using this code for avoiding the problem.

```cpp
auto mode = sf::VideoMode::getDesktop();
mode.height += 1;

sf::RenderWindow window(mode, "SFML Window", sf::Style::None);
```

**Comment by marukrap** [comment]
And some references here.

https://stackoverflow.com/questions/22259067/opengl-non-exclusive-fullscreen-mode-a-k-a-fullscreen-borderless-window
https://stackoverflow.com/questions/23145217/flickering-when-borderless-window-and-desktop-dimensions-are-the-same
https://github.com/glfw/glfw/issues/527
https://steamcommunity.com/app/379720/discussions/0/208684375410727726/

**Comment by eXpl0it3r** [comment]
Would be nice if Microsoft actually documented their "features".

> If anyone is still interested in a more "proper" sort of solution, disabling window flag WS_POPUP fixes this problem. I don't exactly know why though, but this is a general problem with fullscreen OpenGL applications on Windows.

At least we now know how to "fix" it, even though I'm not sure if that flag is required or not.

**Comment by marukrap** [comment]
Oh, I missed that comment, I was struggling with OpenGL things...
It seems the solutions works well.

**Comment by naezith** [comment]
Still looking forward for this.

**Comment by eXpl0it3r** [comment]
@LaurentGomila Do you remember whether [`WS_POPUP`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632600%28v=vs.85%29.aspx) is needed or if it could potentially be removed?

**Comment by LaurentGomila** [comment]
Of course not 😬

**Comment by Foaly** [comment]
I wanted to start the windows implementation for the window states this evening. I might be able to give this a try if I remember.
@naezith If you're looking forward to this, why not do some tests/implement it yourself 😀

**Comment by naezith** [comment]
I am not good enough to contribute about something like this. Also I just released my game Remnants of Naezith, being solo developer makes me have something to do about the game all the time.

Regards,

Tolga Ay
gamedev @ Remnants of Naezith

On Feb 7, 2018, 5:16 PM +0300, Foaly <notifications@github.com>, wrote:

I wanted to start the windows implementation for the window states this evening. I might be able to give this a try if I remember.
@naezith<https://github.com/naezith> If you're looking forward to this, why not do some tests/implement it yourself 😀

**Comment by Foaly** [comment]
I had a quick test and it seems like without `WS_POPUP` a border is created around the window. I might have found another solution though. Will send a pull request tomorrow.

**Comment by eXpl0it3r** [comment]
This seems to be some change with swap chains and how DWM is taking itself out of the equation when the window fully covers the screen.

I'm not sure if simply removing `WS_POPUP` is a good fix or just some hack. What's certain, is that this needs some further digging. I'll leave a list of resources here, that anyone can pick up and figure out, what's the best approach.

- [YouTube: DX12 different presentation modes in Windows 10](https://www.youtube.com/watch?v=E3wTajGZOsA)
- [DX12 fullscreen switching example](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Fullscreen/src/Win32Application.cpp#L92)
- [Nvidia DX12 Do's and Don'ts](https://developer.nvidia.com/dx12-dos-and-donts#swapchains)

**Comment by JonnyPtn** [comment]
I'm not able to reproduce any issues on latest code using VS2022 and windows 11 - I'm not aware of any SFML changes that would have affected this, so wondering if it's been fixed elsewhere. Is anybody else able to check?

**Comment by Windblade-GR01** [comment]
On my end it seems to still happen.
On top of this the WS_POPUP fix does work on NVidia but not Intel.
And is not like is an old driver as the laptop I'm testing is using 13th gen Intel and the lastest Win11.

Testing on my end by messing up with every single Window style and even EX Styles.
Enabling the WS_EX_APPWINDOW flag seems to fix it for Intel.
Interestingly enough WS_POPUP does seem not affect Intel, unlike NVIDIA.

So, we want to enable "WS_EX_APPWINDOW" too on top of disabling "WS_POPUP".
As to fix borderless mode on both GPUS.

Based on this I guess that the window flags that enable FSE (and prevent borderless from working) seem to change per-vendor.
So will need someone with an AMD GPU to test on their end too.
