### ISSUE TITLE
Building a Unix backend on Darwin, few linking errors in Window: Undefined symbols:   `__ZN2sf4priv10GlxContextD1Ev`, referenced from: `__ZNSt22_Optional_payload_baseIN2sf4priv10GlxContextEE8_M_resetEv` in GlContext.cpp.o, etc.

### ISSUE THREAD

**Issue by barracuda156** [SFML/SFML#2641]
I am trying to fix the build with GCC on Darwin, and for now I want to use a generic Unix implementation for Window rather than ever-broken ObjC.
Generally speaking, most of the code builds effortlessly.

After fixing includes in Window, it also mostly builds, however several symbols are not found. I have tried both the master branch and 2.6.0 release – same result.
This is from the master:
```
[ 48%] Linking CXX shared library ../../../lib/libsfml-window.dylib
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_sfml/sfml-devel/work/build/src/SFML/Window && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/sfml-window.dir/link.txt --verbose=ON
/opt/local/bin/g++-mp-12 -pipe -Os -fpermissive -Wno-sign-conversion -DNDEBUG -I/opt/local/include -arch ppc -mmacosx-version-min=10.6 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -compatibility_version 3.0.0 -current_version 3.0.0 -o ../../../lib/libsfml-window.3.0.0.dylib -install_name @rpath/libsfml-window.3.0.dylib "CMakeFiles/sfml-window.dir/Clipboard.cpp.o" "CMakeFiles/sfml-window.dir/Context.cpp.o" "CMakeFiles/sfml-window.dir/Cursor.cpp.o" "CMakeFiles/sfml-window.dir/GlContext.cpp.o" "CMakeFiles/sfml-window.dir/GlResource.cpp.o" "CMakeFiles/sfml-window.dir/Joystick.cpp.o" "CMakeFiles/sfml-window.dir/JoystickManager.cpp.o" "CMakeFiles/sfml-window.dir/Keyboard.cpp.o" "CMakeFiles/sfml-window.dir/Mouse.cpp.o" "CMakeFiles/sfml-window.dir/Touch.cpp.o" "CMakeFiles/sfml-window.dir/Sensor.cpp.o" "CMakeFiles/sfml-window.dir/SensorManager.cpp.o" "CMakeFiles/sfml-window.dir/VideoMode.cpp.o" "CMakeFiles/sfml-window.dir/Vulkan.cpp.o" "CMakeFiles/sfml-window.dir/Window.cpp.o" "CMakeFiles/sfml-window.dir/WindowBase.cpp.o" "CMakeFiles/sfml-window.dir/WindowImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/CursorImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/ClipboardImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/InputImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/KeyboardImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/KeySymToKeyMapping.cpp.o" "CMakeFiles/sfml-window.dir/Unix/KeySymToUnicodeMapping.cpp.o" "CMakeFiles/sfml-window.dir/Unix/SensorImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/Display.cpp.o" "CMakeFiles/sfml-window.dir/Unix/VideoModeImpl.cpp.o" "CMakeFiles/sfml-window.dir/Unix/VulkanImplX11.cpp.o" "CMakeFiles/sfml-window.dir/Unix/WindowImplX11.cpp.o" "CMakeFiles/sfml-window.dir/OpenBSD/JoystickImpl.cpp.o"  -Wl,-rpath,/opt/local/lib /opt/local/lib/libX11.dylib /opt/local/lib/libXrandr.dylib /opt/local/lib/libXcursor.dylib ../../../lib/libsfml-system.3.0.0.dylib -framework Foundation -framework AppKit -framework IOKit -framework Carbon -latomic /opt/local/lib/libXext.dylib /opt/local/lib/libXrender.dylib /opt/local/lib/libXfixes.dylib /opt/local/lib/libX11.dylib -Wl,-framework,OpenGL 
Undefined symbols:
  "__ZN2sf4priv10GlxContextD1Ev", referenced from:
      __ZNSt22_Optional_payload_baseIN2sf4priv10GlxContextEE8_M_resetEv in GlContext.cpp.o
  "__ZN2sf4priv10GlxContext11getFunctionEPKc", referenced from:
      __ZN2sf4priv9GlContext11getFunctionEPKc in GlContext.cpp.o
  "__ZN2sf4priv10GlxContextC1EPS1_", referenced from:
      __ZN2sf4priv9GlContext6createEv in GlContext.cpp.o
      __ZN2sf4priv9GlContext13SharedContextC4Ev in GlContext.cpp.o
  "__ZN2sf4priv10GlxContext16selectBestVisualEP9_XDisplayjRKNS_15ContextSettingsE", referenced from:
      __ZN2sf4priv13WindowImplX11C4ENS_9VideoModeERKNS_6StringEmRKNS_15ContextSettingsE in WindowImplX11.cpp.o
  "__ZN2sf4priv10GlxContextC1EPS1_RKNS_15ContextSettingsERKNS_7Vector2IjEE", referenced from:
      __ZN2sf4priv9GlContext6createERKNS_15ContextSettingsERKNS0_10WindowImplEj in GlContext.cpp.o
      __ZN2sf4priv9GlContext6createERKNS_15ContextSettingsERKNS_7Vector2IjEE in GlContext.cpp.o
      __ZN2sf4priv9GlContext6createERKNS_15ContextSettingsERKNS_7Vector2IjEE in GlContext.cpp.o
  "__ZN2sf4priv10GlxContextC1EPS1_RKNS_15ContextSettingsERKNS0_10WindowImplEj", referenced from:
      __ZN2sf4priv9GlContext6createERKNS_15ContextSettingsERKNS0_10WindowImplEj in GlContext.cpp.o
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libsfml-window.3.0.0.dylib] Error 1
```
I have looked into the sources, but it is not clear, why this specifically should fail. Some linking flag missing?

Sources are mostly untouched: what I obviously had to do is remove hardcoding in CMakeLists which is breaking the build and switch includes in Window, so that ObjC stuff is not pulled into Unix sources, but appropriate headers are used. That is all.

(Before someone asks: yes, I see that sources for joystick are picked from OpenBSD directory, that is intended, since they are the most basic and do not pull in proprietary headers. In any case, the error does not seem to be caused by joystick module.)

P. S. There are a few instances where source code seem to have minor bugs (so with -Werror it gonna fail), like:
```
 SocketSelector.cpp:110: error: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
 InputImpl.cpp: error: invalid conversion from 'sf::WindowHandle' {aka 'void*'} to 'Window' {aka 'long unsigned int'} [-fpermissive]
```

**Comment by ChrisThrasher** [comment]
I doubt that a PR that adds an entirely new windowing backend to macOS is prone to be accepted so I wouldn't go too far down that route if I were you.

This is the actual error when you try to use GCC with SFML:
```
[build] In file included from /Users/thrasher/Projects/sfml/src/SFML/Window/macOS/JoystickImpl.hpp:33,
[build]                  from /Users/thrasher/Projects/sfml/src/SFML/Window/JoystickImpl.hpp:84,
[build]                  from /Users/thrasher/Projects/sfml/src/SFML/Window/JoystickManager.hpp:31,
[build]                  from /Users/thrasher/Projects/sfml/src/SFML/Window/Joystick.cpp:29:
[build] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDDevice.h:273:34: error: 'dispatch_block_t' has not been declared
[build]   273 |                                  dispatch_block_t               handler)
[build]       |                                  ^~~~~~~~~~~~~~~~
```
If you want to use GCC on macOS, this is what you should look into fixing.

**Comment by barracuda156** [comment]
@ChrisThrasher Well, this will not work, blocks are clangisms and at the moment unsupported in GCC. Upstream considers implementing them, but not in a high priority, AFAIU.
Here is the ticket: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78352

Furthermore, `libdispatch` is not there on PowerPC, as well as Intel on 10.5 and earlier. Anything using dispatch semaphores needs a fallback to mach or POSIX ones. (And yeah, `libdispatch` uses blocks.)

**Comment by ChrisThrasher** [comment]
> blocks are clangisms and at the moment unsupported in GCC. Upstream considers implementing them, but not in a high priority

That's really useful context. Sounds like SFML supporting GCC on macOS is even harder than I suspected.

What's your particular use case for using GCC on macOS? Is using Clang unacceptable or merely undesirable?

**Comment by barracuda156** [comment]
@ChrisThrasher Using clang on PowerPC is impossible – it has been incapable of generating a working code since its beginning, and clangs after clang-7 won’t even build. (Building is likely fixable with moderate efforts, but no point in that, unless PowerPC ABI is fixed – and restored, since upstream trashed it in some recent version completely.)

Outside of PowerPC, it is desirable for any opensource code to support multiple compilers and do not depend on any single one. Say, requiring specifically GCC would be just as bad as requiring specifically Clang.

**Comment by Bambo-Borris** [comment]
> @ChrisThrasher Using clang on [Darwin] PowerPC is impossible – it has been incapable of generating a working code since its beginning, and clangs after clang-7 won’t even build. (Building is likely fixable with moderate efforts, but no point in that, unless PowerPC ABI is fixed – and restored, since upstream trashed it in some recent version completely.)
> 
> Outside of PowerPC, it is desirable for any opensource code to support multiple compilers and do not depend on any single one. Say, requiring specifically GCC would be just as bad as requiring specifically Clang.

Does this issue occur with releases prior to 2.6.0, such as 2.5.1 (which was the stable release for a number of years).

**Comment by eXpl0it3r** [comment]
Comments on the issue:

> After fixing includes in Window, it also mostly builds, however several symbols are not found. 

Seems like something went wrong with linking the source code. Since you didn't link to the changes, it's impossible for us to tell what exactly.

This is also not really an SFML issue, but something in your experimental rewrite and thus would fit better in the help section of the forum or discussed on Discord.

> There are a few instances where source code seem to have minor bugs (so with -Werror it gonna fail)

Feel free to create a PR for them, to fix them.

----

Discussion comments:

> Using clang on [Darwin] PowerPC is impossible

Since you seem to be on a mission to fix stuff for PowerPC, what kind of systems/devices are you working with/for?

Note that while you're free to spend your time fixing things up for PowerPC, you can't expect every project to align with your view and invest their time in getting stuff fixed by themselves or adding additional complexity and maintenance effort.

> Does this issue occur with releases prior to 2.6.0, such as 2.5.1

As far as I know, GCC has been broken for a long time and I don't expect it to work with SFML 2.5.1 either. One report goes back to 2017: #1229

> Outside of PowerPC, it is desirable for any opensource code to support multiple compilers and do not depend on any single one.

While I agree with this in a general sense, the cost for achieving it, can't be underestimating. Writing a whole new backend just to provide GCC support, might not be desirable.

**Comment by barracuda156** [comment]
> > @ChrisThrasher Using clang on [Darwin] PowerPC is impossible – it has been incapable of generating a working code since its beginning, and clangs after clang-7 won’t even build. (Building is likely fixable with moderate efforts, but no point in that, unless PowerPC ABI is fixed – and restored, since upstream trashed it in some recent version completely.)
> > Outside of PowerPC, it is desirable for any opensource code to support multiple compilers and do not depend on any single one. Say, requiring specifically GCC would be just as bad as requiring specifically Clang.
> 
> Does this issue occur with releases prior to 2.6.0, such as 2.5.1 (which was the stable release for a number of years).

@Bambo-Borris I can check that. I have only tried 2.6.0 (what Macports has) and the master (to verify errors were not fixed already).

**Comment by barracuda156** [comment]
@eXpl0it3r 

> Note that while you're free to spend your time fixing things up for PowerPC, you can't expect every project to align with your view and invest their time in getting stuff fixed by themselves or adding additional complexity and maintenance effort.

Absolutely. However nothing in my query is arch-specific, I believe. I could be wrong, but from the look of things none of errors I encountered so far are caused by PowerPC target.

(Regardless of that, I perfectly understand that no one is obliged to support anything, it is opensource. I do believe though that a healthy code should work on any sane platform, and PowerPC is/was one of such. And fixing errors which currently show up only on a specific config is still fixing actual bugs, which benefits the code in general.)

> While I agree with this in a general sense, the cost for achieving it, can't be ignored. Writing a whole new backend just to provide GCC support, might not be desirable.

I agree here as well, and neither I am going to write a new backend from scratch :) The question is not about a new backend though: if Unix code works with zero modifications on several versions of *BSD and Linux (aside of joystick module), it presumably should work on MacOS too.
If that is not the case for some legit reason, issue can be closed. Nobody will implement MacOS support specifically for my arch or even for GCC anew, we all know that. But it the existing backend can be fixed for MacOS/GCC with _subjectively reasonable_ effort, it is arguably worth doing and will benefit at least some end-users.

> As far as I know, GCC has been broken for a long time and I don't expect it to work with SFML 2.5.1 either.

I would not bother trying to fix Obj C backend for GCC, to be honest. Neither I expect anyone to do that. If the implementation uses `libdispatch` and blocks, it is non-trivial to make it work. Possible, but kinda unreasonable, and should be done on a level of a) GCC upstream, for blocks and b) Macports, for `libdispatch`.
So I suggest ignore Cocoa backend here. It will not work.

> Since you seem to be on a mission to fix stuff for PowerPC, what kind of systems/devices are you working with/for?

I am one of the few people maintaining PowerPC systems in Macports :)

**Comment by ChrisThrasher** [comment]
> I do believe though that a healthy code should work on any sane platform, and PowerPC is/was one of such.

We will not be making changes to SFML to support PowerPC Macs. I'm sorry that's a disappointing answer but that hardware platform is much too old to justify spending our limited development resources supporting it. SFML 2 development is frozen while SFML 3 development is only supporting the current generation of OSes so it's safe to say PowerPC Mac OS X will not make the cut.

If you want to fork an older release of SFML so that it works on PowerPC Macs then you can reach out to us on Discord and we'll be happy to help you work through whatever issues you encounter.

**Comment by barracuda156** [comment]
@ChrisThrasher Thank you. As I said above, I do not ask or expect (and do not need either) any PowerPC-specific support. What I was interested in is getting generic Unix backend to work with GCC on macOS. It is perfectly fine to do that on Intel and on a newer OS.

**Comment by ChrisThrasher** [comment]
In practice you're asking for PowerPC-specific support since nobody else has asked to use X11 on macOS.

**Comment by barracuda156** [comment]
> In practice you're asking for PowerPC-specific support since nobody else has asked to use X11 on macOS.

Well, I can try building this on x86_64, no issues. Can update on the result in a day or two – I need to get to the Intel machine with functional set-up. If everything builds fine on Intel with GCC, I will apologize – I understand it is indeed unreasonable to ask for any arch-specific support.

**Comment by eXpl0it3r** [comment]
> The question is not about a new backend though: if Unix code works with zero modifications on several versions of *BSD and Linux (aside of joystick module), it presumably should work on MacOS too.

I don't exactly see how this should work. The window module on Linux uses X11 (or [DRM](https://en.wikipedia.org/wiki/Direct_Rendering_Manager)), so I don't see how that would work with macOS's OS APIs, unless you're suggesting to run an X-server on macOS and let that handle the macOS API calls. In that case, I can't really stand behind such a move, since I've never heard anyone running X-server on macOS and knowing Apple's API and the X11 protocol, I *highly* doubt this will just work out of the box, because SFML has a lot of Linux specific workarounds.

> If everything builds fine on Intel with GCC

As mentioned, there are issues with GCC, but not all of them are fixable, as they fail somewhere in GCC headers. SFML runs fine on Intel chips set though, we've only just added support for ARM64 chips.

**Comment by barracuda156** [comment]
(Just to be clear, I did not suggest to _replace_ native backend with X11 one, of course.)

X11 have been supported on Apple for ages, by Apple itself originally (it was a component of macOS), and then by Xquartz. It certainly works right now, and on x86 it should be robust.
I do not have global statistics of users of X11 on macOS, but even locally in MacPorts it is installed by many: 
https://ports.macports.org/port/xorg-server/stats (statistics by OS version and arch)
