### ISSUE TITLE
Error in compiling and calling static library under Windows

### ISSUE THREAD

**Issue by jimwang118** [SFML/SFML#3308]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

When I use the latest version of sfml, compile the static library under Windows, and then use the following statement to call it, the following error occurs.
```
find_package(SFML COMPONENTS system window graphics audio CONFIG REQUIRED)
target_link_libraries(web PRIVATE sfml-system sfml-network sfml-graphics sfml-window sfml-audio)
```
Error:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfigDependencies.cmake:42 (set_property):
  set_property could not find TARGET OpenAL.  Perhaps it has not yet been
  created.		E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfigDependencies.cmake	42		

```

### Your Environment

- OS / distro / window manager: Windows
- SFML version: 2.6.2
- Compiler / toolchain: vs2022
- Special compiler / CMake flags: cmake 3.30.1

### Steps to reproduce

1. git clone vcpkg
2. Replaced version 2.6.2.
3. vcpkg install sfml:x64-windows-static
4. Call the generated sfml library.
5.Create a vs cmake project, then call sfml in the project to compile the project, and an error occurs.

```
add_executable (web "web.cpp" "web.h")
find_package(SFML COMPONENTS system window graphics audio CONFIG REQUIRED)
target_link_libraries(web PRIVATE sfml-system sfml-network sfml-graphics sfml-window sfml-audio)
```

### Expected behavior

The compiled result can be called normally.

### Actual behavior

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfigDependencies.cmake:42 (set_property):
  set_property could not find TARGET OpenAL.  Perhaps it has not yet been
  created.		E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfigDependencies.cmake	42

**Comment by eXpl0it3r** [comment]
Sounds more like vcpkg dependency patching is failing here. Since vcpkg will hack its own OpenAL version into the detection, one needs to make sure it can be found.

I hope, vcpkg doesn't allow for static OpenAL libs, because that will cause a lot of licensing problems, which is why SFML has never supported that scenario.

SFML hasn't changed anything on the OpenAL detection code between 2.6.1 and 2.6.2. Maybe the patch doesn't work anymore due to other changes?

**Comment by jimwang118** [comment]
Yes, the patch does not complete the functional fix. The same patch has no problem on 2.6.1. This problem only occurs when statically compiling.

**Comment by jimwang118** [comment]
```
1> CMake generation started for configuration: 'x64-Release'.
1> Command line: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="E:\workspace\web\out\install\x64-Release" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="E:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-static"   "E:\workspace\web" 2>&1"
1> Working directory: E:\workspace\web\out\build\x64-Release
1> [CMake] -- Selecting Windows SDK version 10.0.26100.0 to target Windows 10.0.19045.
1> [CMake] -- The C compiler identification is MSVC 19.41.34123.0
1> [CMake] -- The CXX compiler identification is MSVC 19.41.34123.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Found ZLIB: optimized;E:/vcpkg/installed/x64-windows-static/lib/zlib.lib;debug;E:/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib (found version "1.3.1")
1> [CMake] -- Found BZip2: optimized;E:/vcpkg/installed/x64-windows-static/lib/bz2.lib;debug;E:/vcpkg/installed/x64-windows-static/debug/lib/bz2d.lib (found version "1.0.8")
1> [CMake] -- Looking for BZ2_bzCompressInit
1> [CMake] -- Looking for BZ2_bzCompressInit - found
1> [CMake] -- Found PNG: optimized;E:/vcpkg/installed/x64-windows-static/lib/libpng16.lib;debug;E:/vcpkg/installed/x64-windows-static/debug/lib/libpng16d.lib (found version "1.6.43")
1> [CMake] -- Found OpenAL: E:/vcpkg/installed/x64-windows-static/debug/lib/OpenAL32.lib
1> [CMake] CMake Error at E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfigDependencies.cmake:42 (set_property):
1> [CMake]   set_property could not find TARGET OpenAL.  Perhaps it has not yet been
1> [CMake]   created.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfigDependencies.cmake:87 (sfml_bind_dependency)
1> [CMake]   E:/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfig.cmake:122 (include)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   web/CMakeLists.txt:7 (find_package)
1> [CMake] -- Found SFML 2.6.2 in E:/vcpkg/installed/x64-windows-static/share/sfml
1> [CMake] -- Configuring incomplete, errors occurred!
1> 'C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="E:\workspace\web\out\install\x64-Release" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="E:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-static"   "E:\workspace\web" 2>&1"' execution failed with error: ''C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="E:\workspace\web\out\install\x64-Release" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="E:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-static"   "E:\workspace\web" 2>&1"' returned with exit code: 1'.
```
Looking at the compilation output process, the openal32.lib library was found, but an error occurred in set_property.

**Comment by jimwang118** [comment]
I have fixed this issue in vcpkg, please see if it can be synchronized to your code.
https://github.com/microsoft/vcpkg/pull/42118

**Comment by Zombieschannel** [comment]
I can confirm I have the same issue with static builds on Windows, however I am not (or at least I think so) using vcpkg. I'm just following the official "Compiling SFML with CMake" tutorial.
So unless it is using vcpkg behind my back, the issue is something else since the exact same steps with 2.6.1 or 2.6.0 work fine.

**Comment by Zombieschannel** [comment]
This commit seems to have broken OpenAL for whatever reason https://github.com/SFML/SFML/pull/3194

**Comment by JonnyPtn** [comment]
I'm not overly fussed about the vcpkg patches - they're always required to some degree and I don't think we should consider bringing them upstream, especially for an old version

However, it of course should work as part of the normal cmake install/find_package workflow. Testing this on latest 2.6.x branch I can't reproduce any issues - I'm building and installing the sfml static libs then using `find_package(...)` in a project and it all builds

@Zombieschannel  could you test again on the latest 2.6.x branch and if it still reproduces provide a bit more detail about the setup/steps?

**Comment by Zombieschannel** [comment]
I can confirm that I still have the same issue on either 2.6.2 or latest 2.6.x:

```
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.26100.
CMake Error at C:/Users/cutel/source/repos/SFML-2.6.test-x86/lib/cmake/SFML/SFMLConfigDependencies.cmake:40 (set_property):
  set_property could not find TARGET OpenAL.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  C:/Users/cutel/source/repos/SFML-2.6.test-x86/lib/cmake/SFML/SFMLConfigDependencies.cmake:78 (sfml_bind_dependency)
  C:/Users/cutel/source/repos/SFML-2.6.test-x86/lib/cmake/SFML/SFMLConfig.cmake:117 (include)
  CMakeLists.txt:72 (find_package)


-- Found SFML 2.6.2 in C:/Users/cutel/source/repos/SFML-2.6.test-x86/lib/cmake/SFML
-- Configuring incomplete, errors occurred!
```
I'm using Visual Studio 17 2022 build tools, below is the part of an automated script that I used for a while but it does not do anything special, just build both static and shared...

```
cmake .. -A Win32 -G "Visual Studio 17 2022" !ADDITIONAL_CONFIG! --fresh
cmake -DBUILD_SHARED_LIBS=true .
cmake --build . -j 32 --config Debug
cmake --install . --config Debug --prefix=../../../SFML-!SFML_VER!-!build!
cmake --build . -j 32 --config Release
cmake --install . --config Release --prefix=../../../SFML-!SFML_VER!-!build!
cmake -DBUILD_SHARED_LIBS=false .
cmake --build . -j 32 --config Debug
cmake --install . --config Debug --prefix=../../../SFML-!SFML_VER!-!build!
cmake --build . -j 32 --config Release
cmake --install . --config Release --prefix=../../../SFML-!SFML_VER!-!build!
```

I'm not sure what could be wrong, do you have `set(SFML_STATIC_LIBRARIES TRUE)` before your `find_package(...)`?

**Comment by JonnyPtn** [comment]
Yea I am, there's a separate error that would hit for that

I'm also using VS2022, so yeah quite confusing... which cmake version are you on?

**Comment by Zombieschannel** [comment]
I'm using: cmake version 3.31.6-msvc6

**Comment by eXpl0it3r** [comment]
This should be fixed with #3651
